version: "3.9"
# Netbootxyz stack
# Page: https://netboot.xyz/
# Code: https://github.com/netbootxyz/docker-netbootxyz
# netboot.xyz is a convenient place to boot into any type of operating system
# or utility disk without the need of having to go spend time retrieving the
# ISO just to run it. iPXE is used to provide a user friendly menu from within
# the BIOS that lets you easily choose the operating system you want along
# with any specific types of versions or bootable flags.

services:

  app:
    image: ghcr.io/netbootxyz/netbootxyz
    volumes:
      - /etc/netbootxyz:/config
      - /var/netboot:/assets
    ports:
      - 3000:3000
      - 69:69/udp
      - 31394:80
    restart: unless-stopped
    cap_add: # More info: https://github.com/samdbmg/dhcp-netboot.xyz
      - NET_ADMIN